// Mock data for the Pulse chat application

export const currentUser = {
  id: "u_me",
  displayName: "Ava Sinclair",
  username: "ava.s",
  avatarColor: "from-rose-400 to-orange-300",
  initials: "AS",
  bio: "Design systems & late-night espresso ✨",
  phone: "+1 (415) 555 0188",
};

export const conversations = [
  {
    id: "c1",
    name: "Mira Okafor",
    username: "mira.o",
    initials: "MO",
    avatarColor: "from-violet-500 to-fuchsia-400",
    lastMessage: "Just shipped the prototype — wanna peek?",
    time: "2m",
    unread: 3,
    online: true,
    pinned: true,
    typing: false,
  },
  {
    id: "c2",
    name: "Studio Crescent",
    username: "studio.crescent",
    initials: "SC",
    avatarColor: "from-amber-400 to-rose-400",
    lastMessage: "Theo: I'll send the moodboard tonight 🌙",
    time: "14m",
    unread: 1,
    online: true,
    pinned: true,
    typing: true,
    group: true,
  },
  {
    id: "c3",
    name: "Kenji Aramaki",
    username: "kenji.a",
    initials: "KA",
    avatarColor: "from-emerald-400 to-teal-500",
    lastMessage: "Voice message · 0:42",
    time: "1h",
    unread: 0,
    online: false,
    pinned: false,
  },
  {
    id: "c4",
    name: "Lila Marchetti",
    username: "lila.m",
    initials: "LM",
    avatarColor: "from-sky-400 to-indigo-500",
    lastMessage: "Coffee on Thursday? ☕",
    time: "3h",
    unread: 0,
    online: true,
    pinned: false,
  },
  {
    id: "c5",
    name: "Atlas Workspace",
    username: "atlas",
    initials: "AT",
    avatarColor: "from-stone-500 to-zinc-700",
    lastMessage: "Noor: Pushed the new tokens to main",
    time: "Yesterday",
    unread: 0,
    online: false,
    pinned: false,
    group: true,
  },
  {
    id: "c6",
    name: "Iris Bellweather",
    username: "iris.b",
    initials: "IB",
    avatarColor: "from-pink-400 to-rose-500",
    lastMessage: "Loved that shot 🌸",
    time: "Mon",
    unread: 0,
    online: false,
    pinned: false,
  },
];

export const messagesByConversation = {
  c1: [
    { id: "m1", from: "them", text: "Morning ✨ how'd the deck land?", time: "9:12 AM" },
    { id: "m2", from: "me", text: "They loved it — especially the motion bits.", time: "9:14 AM", read: true },
    { id: "m3", from: "them", text: "I knew it. Those micro-interactions are gold.", time: "9:14 AM" },
    { id: "m4", from: "me", text: "Honestly, your prototype set the tone for everything.", time: "9:16 AM", read: true },
    { id: "m5", from: "them", text: "Just shipped the prototype — wanna peek? 👀", time: "9:42 AM" },
  ],
  c2: [
    { id: "m1", from: "them", name: "Theo", text: "Quick sync at 4? Moodboard's almost done.", time: "1:02 PM" },
    { id: "m2", from: "me", text: "Works for me. I'll bring the type explorations.", time: "1:05 PM", read: true },
    { id: "m3", from: "them", name: "Theo", text: "I'll send the moodboard tonight 🌙", time: "1:48 PM" },
  ],
  c3: [
    { id: "m1", from: "them", text: "Track is finally mixed. Sending stems now.", time: "11:20 AM" },
    { id: "m2", from: "me", text: "Yes please 🙏", time: "11:22 AM", read: true },
  ],
  c4: [{ id: "m1", from: "them", text: "Coffee on Thursday? ☕", time: "8:14 AM" }],
  c5: [{ id: "m1", from: "them", name: "Noor", text: "Pushed the new tokens to main", time: "Yesterday" }],
  c6: [{ id: "m1", from: "them", text: "Loved that shot 🌸", time: "Mon" }],
};

export const discoverPeople = [
  { id: "d1", name: "Sasha Lindqvist", username: "sasha.l", initials: "SL", avatarColor: "from-cyan-400 to-blue-500", bio: "Product designer · Stockholm" },
  { id: "d2", name: "Rohan Vatsal", username: "rohan.v", initials: "RV", avatarColor: "from-orange-400 to-red-500", bio: "Indie dev · Bengaluru" },
  { id: "d3", name: "Camille Duret", username: "camille.d", initials: "CD", avatarColor: "from-violet-400 to-purple-600", bio: "Photographer & filmmaker" },
  { id: "d4", name: "Yusuf Demir", username: "yusuf.d", initials: "YD", avatarColor: "from-emerald-400 to-green-600", bio: "Type designer · Istanbul" },
  { id: "d5", name: "Marisol Reyes", username: "mari.r", initials: "MR", avatarColor: "from-rose-400 to-pink-600", bio: "Founder @ Lumen Studio" },
];
